openapi: 3.0.0
info:
  title: ScalarTax
  description: Accounts API Documentation
  version: 1.0.0
  contact:
    name: API Support
    url: http://example.com/support
    email: support@example.com
  termsOfService: http://example.com/terms/
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://{{base_url}}/
    description: Local server
security:
  - BearerAuth: []

paths:
  /scalartax/accounts/:
    post:
      tags:
        - Accounts
      summary: Create Account
      description: This endpoint allows you to create a new ScalarTax Account.
      header: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
        description: Created Account object
        required: true
      responses:
        '201':
          description: Account Created Successfully.
         
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
                example:
                  id: integer
                  name: string
                  subscription: integer
                  createdby_id: null | string
                  updatedby_id: null | string
                  created_at: datetime
                  updated_at: datetime
        '422':
          description: Unprocessable Entity. Validation errors occurred during the creation.
          content:
            application/json:
              schema:
                type: object
                example:
                  errors: [ "Company name can't be blank", "Account status can't be blank" ]
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    get:
      tags:
        - Accounts
      summary: List Accounts
      description: This endpoint retrieves a list of ScalarTax accounts.
      header: []
      responses:
        '200':
          description: OK
          header:
            - key: x-frame-options
              value: SAMEORIGIN
              uuid: ec53bf88-2a67-4d68-bcad-9221efe5699a
            - key: x-xss-protection
              value: "0"
              uuid: 79792303-840b-4783-b3d7-d6cb427b5911
            - key: x-content-type-options
              value: nosniff
              uuid: 06a7f090-4e9e-44e4-9262-c01ac65793c6
            - key: x-permitted-cross-domain-policies
              value: none
              uuid: b4a4a576-cbe8-4770-a45c-bf6c44dec205
            - key: referrer-policy
              value: strict-origin-when-cross-origin
              uuid: 92f23512-c6fe-4d60-a7c0-fa03b7e2dd1a
            - key: content-type
              value: application/json; charset=utf-8
              uuid: 46bad098-affc-4a85-83d2-72951688dfd4
            - key: vary
              value: Accept, Origin
              uuid: 2e4e9ef2-579d-4381-8ecb-62d936572ad9
            - key: etag
              value: W/"ba5e8883681a47444cb1db132a019818"
              uuid: a4cd75af-56bf-4a72-97b2-955bff40ee3b
            - key: cache-control
              value: max-age=0, private, must-revalidate
              uuid: a574141f-eb89-45f7-968f-700da6ee29fd
            - key: x-request-id
              value: 3c595bfd-e970-4cc2-817c-b6084ca808b5
              uuid: 5ad1a525-0a19-4af6-8031-39cb34b1440b
            - key: x-runtime
              value: "0.229474"
              uuid: e68f83e0-61c9-4e31-9ce2-adeab23079e8
            - key: server-timing
              value:
                start_processing.action_controller;dur=0.01, sql.active_record;dur=0.57,
                instantiation.active_record;dur=0.45,
                process_action.action_controller;dur=15.39
              uuid: 56fade47-e47f-4286-91c0-7aae197d21cb
            - key: Content-Length
              value: "1362"
              uuid: 55626897-ab2d-4aa3-bf77-c9711e96ffa7
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
                example:
                  - id: string
                    name: string
                    subscription_id: string
                    created_by_id: string
                    updated_by_id: string
                    effective_date: datetime
                    account_status: string
                    subscription:
                      id: string
                      name: string
                      contract_acceptance_date: datetime
                      contract_termination_date: datetime
                      contract_effective_date: datetime
                      contract_end_date: datetime
                      service_activation_date: datetime
                      service_end_date: datetime
                      status: string
                      billing_cycle: string
                      billing_amount: boolean
                      created_by_id: string
                      updated_by_id: string
                      created_at: datetime
                      updated_at: datetime
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /scalartax/accounts/{id}:
    get:
      tags:
        - Accounts
      summary: Fetch Account
      description: This endpoint retrieves the details of a specific ScalarTax account.
      header: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK.
          header:
              - key: x-frame-options
                value: SAMEORIGIN
                uuid: ed95c705-af13-45e1-a392-e11170edf565
              - key: x-xss-protection
                value: "0"
                uuid: e11e64b6-56ec-4359-ac56-c47b1d2d1927
              - key: x-content-type-options
                value: nosniff
                uuid: 42226139-fa7b-457f-857c-f42747fe4ec6
              - key: x-permitted-cross-domain-policies
                value: none
                uuid: 0e9d136b-75ec-4a5e-afb7-720684779c0e
              - key: referrer-policy
                value: strict-origin-when-cross-origin
                uuid: 48e812d8-21a1-4d9b-a84f-408c19b61963
              - key: content-type
                value: application/json; charset=utf-8
                uuid: cd5ccc2f-c7e1-44b6-be88-b4a590562c09
              - key: vary
                value: Accept, Origin
                uuid: 8baa9ad8-d444-409b-87cf-6fe24fdeff49
              - key: etag
                value: W/"0b9a2001c66edf2122aa463a8a77898d"
                uuid: f732557f-6d34-4ce3-ad22-7227c65335ac
              - key: cache-control
                value: max-age=0, private, must-revalidate
                uuid: 60c2610b-0656-4791-a127-002d368b21cf
              - key: x-request-id
                value: dbda911a-1f15-49a9-854d-abae6f43868f
                uuid: a72f2baf-8cd3-4b29-a1f2-1ce76b632c61
              - key: x-runtime
                value: "0.221737"
                uuid: cfed02f0-eb7d-4d8f-bff6-ccb90448b27d
              - key: server-timing
                value:
                  start_processing.action_controller;dur=0.01, sql.active_record;dur=0.78,
                  instantiation.active_record;dur=0.08,
                  process_action.action_controller;dur=5.70
                uuid: ed337ab4-021f-430c-9abe-e1453c389330
              - key: Content-Length
                value: "170"
                uuid: ca7e5a4e-db81-4cbb-a2ef-8dd3ee565ff2
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
                example:
                  id: string
                  name: string
                  subscription_id: string
                  created_by_id: string
                  updated_by_id: string
                  effective_date: datetime
                  account_status: string
                  subscription:
                    id: string
                    name: string
                    contract_acceptance_date: datetime
                    contract_termination_date: datetime
                    contract_effective_date: datetime
                    contract_end_date: datetime
                    service_activation_date: datetime
                    service_end_date: datetime
                    status: string
                    billing_cycle: string
                    billing_amount: boolean
                    created_by_id: string
                    updated_by_id: string
                    created_at: datetime
                    updated_at: datetime
        '404':
          description: Not Found. Account with that Specific ID not Found.
          content:
            application/json:
              schema:
                type: object
                example:
                  error: Account Not Found.
        '500':
          description: Internal Server Error.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Account:
      type: object
      properties:
        company_name:
          type: string
          description: The name of the company
        account_status:
          type: string
          description: The status of the account (e.g., Active, Inactive)
        username:
          type: string
          description: The username for the account
        first_name:
          type: string
          description: The first name of the user
        last_name:
          type: string
          description: The last name of the user
        email:
          type: string
          format: email
          description: The email address of the user
      required:
        - company_name
        - account_status
        - username
        - first_name
        - last_name
        - email
      xml:
        name: Account
